spring:
 # \u6570\u636E\u6E90\u914D\u7F6E
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/stuclub?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
      username: root
      password: root
  # \u9759\u6001\u8D44\u6E90\u914D\u7F6E
server:
  port: 8888